// Liste gültiger 5-Buchstaben-Wörter (Deutsch, ohne Umlaute/ß) zur Validierung
// von Rateversuchen und des vom Setter gewählten Geheimworts.
// Kann jederzeit erweitert werden, indem weitere Großbuchstaben-Wörter ergänzt werden.
const WORD_LIST = [
  "AFFEN","ADLER","ACKER","APFEL","ARENA","ATLAS","AUGEN","AUTOS",
  "BAUCH","BAUER","BEBEN","BEERE","BEINE","BEIZE","BERGE","BESEN","BETEN",
  "BIBEL","BIENE","BIRNE","BLATT","BLECH","BLICK","BLITZ","BLUME","BLUSE",
  "BOGEN","BOOTE","BRAND","BRAUN","BREIT","BRIEF","BROTE","BRUCH","BUCHE","BUSSE",
  "CHEFS","CREME",
  "DAMEN","DAUER","DECKE","DEGEN","DENKE","DIEBE","DINGE","DOSEN","DRAHT",
  "DRANG","DROGE","DUMPF","DURST",
  "ECKEN","EHREN","EIMER","EISEN","ELCHE","ENDEN","ENGEL","ENTEN","ERBEN",
  "ERDEN","ERNTE","ERSTE","ESSEN","ETAGE",
  "FABEL","FADEN","FAHNE","FALLE","FARBE","FAUST","FEDER","FELLE","FERSE",
  "FESTE","FEUER","FISCH","FLACH","FLECK","FLUCH","FLUSS","FOLGE","FORST",
  "FRAGE","FRECH","FREIE","FUCHS",
  "GABEL","GARBE","GEBEN","GEHEN","GELBE","GERNE","GEIST","GLANZ","GLATT",
  "GLEIS","GNADE","GRIFF","GROSS","GRUFT","GRUND",
  "HAARE","HALLE","HALME","HALTE","HARFE","HARTE","HASEN","HAUSE","HEBEL",
  "HEFTE","HEIME","HELLE","HELME","HERDE","HEUTE","HOFES","HOLEN","HONIG",
  "HORST","HOSEN","HUNDE","HUSTE",
  "IDEEN","IMKER","INSEL",
  "JACKE","JAGEN","JAHRE","JUNGE",
  "KABEL","KAMIN","KANAL","KANNE","KARTE","KASSE","KATZE","KEGEL","KEIME",
  "KELCH","KERZE","KETTE","KISTE","KLANG","KLARE","KLEID","KLEIN","KLIMA",
  "KLOTZ","KNABE","KNOPF","KOHLE","KOSTE","KRAFT","KRANK","KRAUT","KREIS",
  "KREUZ","KRIEG","KRONE","KUGEL","KUNST",
  "LACHE","LADEN","LAGER","LAMPE","LANGE","LARVE","LASSE","LAUFE","LAUTE",
  "LEDER","LEERE","LEGEN","LEHRE","LEISE","LEUTE","LICHT","LIEBE","LINIE",
  "LINKE","LISTE","LOCKE","LOGIK",
  "MAGEN","MALER","MANGO","MARKE","MARKT","MASSE","MAUER","MEERE","MEIST",
  "MELDE","MENGE","MESSE","METER","MIETE","MILCH","MINUS","MONAT","MOTOR",
  "MUSIK",
  "NABEL","NACHT","NADEL","NAGEL","NAMEN","NASEN","NEBEL","NEFFE","NETZE",
  "NEUEN","NICHT","NOTEN","NUTZE",
  "OFFEN","OHREN","ONKEL","OPFER","ORDEN","ORTES","OSTEN",
  "PAARE","PAKET","PALME","PAPST","PARKS","PASST","PAUSE","PERLE","PFADE",
  "PFEIL","PFERD","PILZE","PISTE","PLANE","PLATZ","POREN","PREIS","PROBE",
  "PUDEL","PULLI","PUNKT","PUPPE",
  "QUARK","QUOTE",
  "RABEN","RADIO","RASEN","RATTE","RAUCH","REDEN","REGAL","REGEL","REGEN",
  "REICH","REIFE","REIHE","REISE","RENTE","RESTE","RIESE","RINDE","RITZE",
  "ROBBE","ROLLE","ROSEN","RUDER","RUFEN","RUHIG","RUNDE",
  "SAGEN","SAITE","SALAT","SALBE","SAMEN","SAUER","SCHAF","SCHAL","SCHAR",
  "SCHUH","SEELE","SEGEL","SEIFE","SEITE","SIEGE","SINNE","SITTE","SONNE",
  "SORGE","SOSSE","SPASS","SPEER","SPIEL","SPITZ","SPORT","STADT","STALL",
  "STAMM","STAND","STARK","START","STAUB","STEIN","STERN","STIER","STIFT",
  "STILL","STOFF","STOLZ","STROH","STROM","STUBE","STUFE","STUHL","STURM",
  "STURZ",
  "TABAK","TAFEL","TAKTE","TALER","TANNE","TANTE","TASSE","TASTE","TAUBE",
  "TEICH","TEILE","TEMPO","THEMA","TIGER","TINTE","TISCH","TITEL","TONNE",
  "TORTE","TRAUM","TREND","TREUE","TRIEB","TRUPP",
  "UHREN","UMWEG","UNION","UNTEN",
  "VASEN","VATER","VIDEO","VIRUS","VOGEL","VOLLE","VORNE",
  "WAAGE","WAFFE","WAGEN","WALZE","WANDE","WANGE","WEGEN","WEISE","WELLE",
  "WENDE","WERKE","WESEN","WESTE","WETTE","WIESE","WILLE","WINDE","WIRTE",
  "WOCHE","WOLKE","WOLLE","WORTE","WUNDE","WURST",
  "ZANGE","ZEBRA","ZEHEN","ZEILE","ZELLE","ZELTE","ZEUGE","ZIEGE","ZIELE",
  "ZITAT","ZWANG","ZWECK","ZWEIG","ZWERG"
];

const WORD_SET = new Set(WORD_LIST);
const WORD_LENGTH = 5;

function isValidWord(word) {
  return WORD_SET.has(word.toUpperCase());
}
